### PR TITLE
Adding scripts that creates YAML file for multi-tile layout

### PR DESCRIPTION
**Pull request by soleti**
This script produces a YAML file containing one variable and three dictionaries, describing the physical structures (e.g. pixel pads and anode tiles) and software/electrical associations (e.g. IO group, IO channel, chip ID) for a multi-tile LArPix anode

- `pixel_pitch`: pixel pitch value in mm
- `tile_positions`: dictionary where the key is tile ID of type integer and the value is a pair of vectors: position and orientation of the tile
- `tile_chip_to_io`: nested dictionary where the first key is tile ID and the second key is chip ID and the value is IO channel + 1000 * IO group. Tile ID, chip ID, IO channel, and IO group are all type integers
- `chip_channel_to_position`: dictionary where the key is channel ID + 1000 * chip ID and the value is (x-position, y-position), stored as multiples of the pixel pitch of type integer

### CODE REVIEW

**Comment by samkohn** [comment]
I'm excited to see a pull request for the long-overlooked larpix-geometry! (Yes I still get these alerts...)

I was wondering if you've considered alternatives to the ``channel_ID + 1000*chip_ID`` formulation. In the ``tile_chip_to_io`` dictionary this could be done by making the values lists of length 2, i.e. ``[IO_channel, IO_group]``. And for the keys in ``chip_channel_to_position``, this could be done by using a nested dictionary structure similar to ``tile_chip_to_io``. This way you don't have to worry about mod or integer division to extract the underlying values.

(I'm not sure if the x + 1000*y is already implemented somewhere else and you're just conforming to the interface, or if this is a new decision.)

Separately....
The use of integer division (//) to extract the row and column is reasonable, but part of me is concerned about off-by-1 errors due to the floating point precision. I assume you've tested the script on the specific layout-2.4.0.yaml file it's designed for, but it really is pretty risky. For instance, on my computer 1 / 0.1 returns 10.0 as it should, but 1 // 0.1 returns 9.0. More troubling is that 4.434 * 99 // 4.434 returns 98.0, and that's using the same value as PIXEL_PITCH is set to in the script. I'd pretty strongly recommend using a different way to obtain the row and column, such as ``[round(pixel.x / PIXEL_PITCH), round(pixel.y / PIXEL_PITCH)]``. The ``round`` function (builtin, no imports needed) rounds to the nearest integer and returns an int.

**Comment by soleti** [comment]
Thank you very much Sam for the comments. I am not sure about the `channel_ID + 1000*chip_ID` formulation. I don't have any particular prejudice about the solution you envisioned. @russellphysics what do you think? 
Regarding the integer division, yes you're perfectly right, I will replace // with `round`.

**Comment by peter-madigan** [comment]
How do you feel about a versioning scheme for the files?

I see there being two independent versions that need to be keep track of somehow: the version of the geometry (so which pixels connect to which chips) and the version of the geometry description (how that information is arranged in the lookup tables). Currently only the geometry description has been versioned (just the filename), but I would propose that you include a couple fields within the file, say `layout_version` and `format_version`, to keep track of this explicitly.

**Comment by samkohn** [comment]
I had a multi-paragraph answer which got rather verbose so maybe instead I'll just keep it short at the risk of sounding pushy. So I hope you all take these as gentle suggestions, especially since I'm not really on the project anymore and you may have other plans that contradict what I think.

- Based on Peter's comment, add 2 fields to the multi-tile ``yaml.dump``: ``'tile_version_lookup': 2.4.0`` (in this case) and ``'multi_tile_version': <X.Y.Z>`` (exact version TBD).
- Decide on and record in ``layouts/__init__.py`` a sensible versioning scheme for multi-tiles: when to increment each of X, Y, and Z for version X.Y.Z. One scheme I just thought of could be that X represents the ASIC version, Y represents the single-tile version (incremented from 0), and Z represents the number of tiles in the layout. So the current multi-tile version would be 2.0.8. A subsequent 4-tile version would be 2.0.4. If a new tile is produced, the new 8-tile layout would be 2.1.8. When LArPix v3 comes out the versions would bump to 3.0.8. But really any self-consistent scheme would work fine. (The one I suggested fails if you have 2 different arrangements of 8 tiles, so it's not quite ready for prime time.)
- Remove the ``chip_channel_to_position`` field entirely from the YAML output. Its contents can be computed from the existing information in the file. (You could create a function to do that computation and put it in ``layouts/__init__.py``.)
- The ``pixel_pitch`` field also seems redundant to me since it can be computed based on the individual pixel positions. But if you want to include it for convenience I don't see a problem.

**Comment by soleti** [comment]
Hi Sam,

I agree with the first two points, but I don't follow the third one. If we remove `chip_channel_to_position` how do we go from chip channel to position? I want this file to be used without the layout file, so the end user has to load only one YAML. Does it make sense?

**Comment by samkohn** [comment]
If you want to keep it to a single file then yes, it would make sense to duplicate the data.

**Comment by soleti** [comment]
In the latest commit I read the IO channels from a JSON network configuration file as suggested by @russellphysics

**Comment by soleti** [comment]
I updated the code to take into account the different orientation of the tiles on the anode and I added a dictionary that maps each tile to a (module ID, anode ID, tile ID within the anode) tuple. A detailed explanation is provided [here](https://docs.google.com/document/d/1z2eVsC4mUhfw9uTi07vDMQz7FVRicQUoAnPDAzz2YIM/edit?usp=sharing).

**Pull request merged**
